//
// Created by ruppet on 11.01.2020.
//

#ifndef uc-sflying-cm-protname-h
#define uc-sflying-cm-protname-h

#ifndef _DEBUG
#define CSGO_ENGINE_0 api->get_requestable(str("csgo_engine_0")).c_str()
#define CSGO_ENGINE_1 api->get_requestable(str("csgo_engine_1")).c_str()
#define CSGO_1 api->get_requestable(str("csgo_1")).c_str()
#define CSGO_2 api->get_requestable(str("csgo_2")).c_str()
#define CSGO_3 api->get_requestable(str("csgo_3")).c_str()
#define CSGO_4 api->get_requestable(str("csgo_4")).c_str()
#define CSGO_5 api->get_requestable(str("csgo_5")).c_str()
#define CSGO_6 api->get_requestable(str("csgo_6")).c_str()
#define CSGO_7 api->get_requestable(str("csgo_7")).c_str()
#define CSGO_8 api->get_requestable(str("csgo_8")).c_str()
#define CSGO_9 api->get_requestable(str("csgo_9")).c_str()
#define CSGO_10 api->get_requestable(str("csgo_10")).c_str()
#define CSGO_11 api->get_requestable(str("csgo_11")).c_str()
#define CSGO_12 api->get_requestable(str("csgo_12")).c_str()
#define CSGO_13 api->get_requestable(str("csgo_13")).c_str()
#define CSGO_14 api->get_requestable(str("csgo_14")).c_str()
#define CSGO_15 api->get_requestable(str("csgo_15")).c_str()
#define CSGO_16 api->get_requestable(str("csgo_16")).c_str()
#define CSGO_17 api->get_requestable(str("csgo_17")).c_str()
#define CSGO_18 api->get_requestable(str("csgo_18")).c_str()
#define CSGO_19 api->get_requestable(str("csgo_19")).c_str()
#define CSGO_20 api->get_requestable(str("csgo_20")).c_str()
#define CSGO_21 api->get_requestable(str("csgo_21")).c_str()
#define CSGO_22 api->get_requestable(str("csgo_22")).c_str()
#define CSGO_23 api->get_requestable(str("csgo_23")).c_str()
#define CSGO_24 api->get_requestable(str("csgo_24")).c_str()
#define CSGO_25 api->get_requestable(str("csgo_25")).c_str()
#define CSGO_26 api->get_requestable(str("csgo_26")).c_str()
#define CSGO_27 api->get_requestable(str("csgo_27")).c_str()
#define CSGO_28 api->get_requestable(str("csgo_28")).c_str()
#define CSGO_29 api->get_requestable(str("csgo_29")).c_str()
#define CSGO_30 api->get_requestable(str("csgo_30")).c_str()
#define CSGO_31 api->get_requestable(str("csgo_31")).c_str()
#define CSGO_32 api->get_requestable(str("csgo_32")).c_str()
#define CSGO_33 api->get_requestable(str("csgo_33")).c_str()
#define CSGO_34 api->get_requestable(str("csgo_34")).c_str()
#define CSGO_35 api->get_requestable(str("csgo_35")).c_str()
#else
#define CSGO_ENGINE_0 str("VEngineClient")
#define CSGO_ENGINE_1 str("engine.dll")
#define CSGO_1 str("VClient")
#define CSGO_2 str("client_panorama.dll")
#define CSGO_3 str("VEngineCvar")
#define CSGO_4 str("vstdlib.dll")
#define CSGO_5 str("GAMEEVENTSMANAGER002")
#define CSGO_6 str("VClientEntityList")
#define CSGO_7 str("VEngineModel")
#define CSGO_8 str("VMaterialSystem")
#define CSGO_9 str("materialsystem.dll")
#define CSGO_10 str("VEngineRenderView")
#define CSGO_11 str("VDebugOverlay")
#define CSGO_12 str("VModelInfoClient")
#define CSGO_13 str("EngineTraceClient")
#define CSGO_14 str("VPhysicsSurfaceProps")
#define CSGO_15 str("vphysics.dll")
#define CSGO_16 str("GameMovement")
#define CSGO_17 str("VClientPrediction")
#define CSGO_18 str("VGUI_Surface")
#define CSGO_19 str("vguimatsurface.dll")
#define CSGO_20 str("localize.dll")
#define CSGO_21 str("VGUI_Panel")
#define CSGO_22 str("vgui2.dll")
#define CSGO_23 str("IEngineSoundClient")
#define CSGO_24 str("0F 11 05 ? ? ? ? 83 C8 01 C7 05 ? ? ? ? 00 00 00 00")
#define CSGO_25 str("8B 0D ? ? ? ? 8B 45 ? 51 8B D4 89 02 8B 01")
#define CSGO_26 str("B9 ? ? ? ? A1 ? ? ? ? FF 10 A1 ? ? ? ? B9")
#define CSGO_27 str("8B 3D ? ? ? ? 8A F9")
#define CSGO_28 str("B9 ? ? ? ? F3 0F 11 04 24 FF 50 10")
#define CSGO_29 str("tier0.dll")
#define CSGO_30 str("g_pMemAlloc")
#define CSGO_31 str("shaderapidx9.dll")
#define CSGO_32 str("A1 ? ? ? ? 50 8B 08 FF 51 0C")
#define CSGO_33 str("Valve001")
#define CSGO_34 str("55 8B EC 83 E4 F8 83 EC 18 56 57 8B F9 89 7C 24 0C")
#define CSGO_35 str("Localize_")
#endif

#endif //uc-sflying-cm-protname-h
